cd %~dp0..\ogredeps
mkdir build
cd build

cmake ../ -DCMAKE_BUILD_TYPE="Release" -DOGREDEPS_BUILD_RAPIDJSON=FALSE -DOGREDEPS_BUILD_SDL2=FALSE -DOGREDEPS_BUILD_OIS=FALSE -DOGREDEPS_BUILD_ZZIPLIB=FALSE -DOGREDEPS_BUILD_AMD_QBS=FALSE -DOGREDEPS_BUILD_NVIDIA_NVAPI=FALSE -DCMAKE_INSTALL_PREFIX="../../ogre/Dependencies/" -G "MinGW Makefiles"

mingw32-make install
mingw32-make clean

